CREATE TABLE users
(
    id                 VARCHAR(255)                NOT NULL,
    user_name          VARCHAR(255)                NOT NULL,
    email_id           VARCHAR(255)                NOT NULL,
    password           VARCHAR(255)                NOT NULL,
    roles              VARCHAR(255)                NOT NULL,
    email_verified     BOOLEAN                     NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    last_login         TIMESTAMP WITHOUT TIME ZONE,
    provider           VARCHAR(255),
    provider_id        VARCHAR(255),
    additional_info_id VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE additional_info
(
    id              VARCHAR(255) NOT NULL,
    english_level   VARCHAR(255),
    native_language VARCHAR(255),
    goal            VARCHAR(255),
    CONSTRAINT pk_additional_info PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(10000)                          NOT NULL,
    revoked    BOOLEAN,
    user_id    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE verify_token
(
    token           VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    delete_date     TIMESTAMP WITHOUT TIME ZONE,
    token_type      VARCHAR(255),
    CONSTRAINT pk_verifytoken PRIMARY KEY (token)
);