CREATE TABLE users
(
    id             VARCHAR(255)                NOT NULL,
    user_name      VARCHAR(255)                NOT NULL,
    email_id       VARCHAR(255)                NOT NULL,
    img_url        VARCHAR(255),
    password       VARCHAR(255)                NOT NULL,
    roles          VARCHAR(255)                NOT NULL,
    email_verified BOOLEAN                     NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    last_login     TIMESTAMP WITHOUT TIME ZONE,
    provider       VARCHAR(255),
    provider_id    VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id          VARCHAR(255)                NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    description VARCHAR(255)                NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id          VARCHAR(255)                NOT NULL,
    category_id VARCHAR(255),
    name        VARCHAR(255)                NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    creator_id  VARCHAR(255),
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id         VARCHAR(255)                NOT NULL,
    room_id    VARCHAR(255)                NOT NULL,
    user_id    VARCHAR(255)                NOT NULL,
    content    VARCHAR(4000),
    image_url  VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_edited  BOOLEAN DEFAULT FALSE       NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE       NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE message_reads
(
    id         VARCHAR(255)                NOT NULL,
    message_id VARCHAR(255)                NOT NULL,
    user_id    VARCHAR(255),
    room_id    VARCHAR(255)                NOT NULL,
    read_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_message_reads PRIMARY KEY (id)
);

CREATE TABLE chat_participants
(
    id        VARCHAR(255)                NOT NULL,
    room_id   VARCHAR(255)                NOT NULL,
    user_id   VARCHAR(255),
    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    leave_at  TIMESTAMP WITHOUT TIME ZONE,
    role      VARCHAR(255),
    CONSTRAINT pk_chat_participants PRIMARY KEY (id)
);

CREATE TABLE activity_logs
(
    id         VARCHAR(255)                NOT NULL,
    user_id    VARCHAR(255),
    action     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_activity_logs PRIMARY KEY (id)
);

CREATE TABLE additional_info
(
    id              VARCHAR(255) NOT NULL,
    english_level   VARCHAR(255),
    native_language VARCHAR(255),
    goal            VARCHAR(255),
    CONSTRAINT pk_additional_info PRIMARY KEY (id)
);

CREATE TABLE user_settings
(
    id                 VARCHAR(255) NOT NULL,
    theme              VARCHAR(255),
    notifications      BOOLEAN      NOT NULL,
    interface_language VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_settings PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(10000)                          NOT NULL,
    revoked    BOOLEAN,
    user_id    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE moderation
(
    id         VARCHAR(255)                NOT NULL,
    room_id    VARCHAR(255),
    moder_id   VARCHAR(255),
    user_id    VARCHAR(255),
    action     VARCHAR(255)                NOT NULL,
    reason     VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_moderation PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         VARCHAR(255)                NOT NULL,
    user_id    VARCHAR(255),
    content    VARCHAR(255)                NOT NULL,
    is_read    BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE verify_token
(
    token           VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    delete_date     TIMESTAMP WITHOUT TIME ZONE,
    token_type      VARCHAR(255),
    CONSTRAINT pk_verifytoken PRIMARY KEY (token)
);