create table if not exists additional_info
(
    id              varchar(255) not null
        primary key,
    english_level   varchar(255)
        constraint additional_info_english_level_check
            check ((english_level)::text = ANY
                   ((ARRAY ['A1'::character varying, 'A2'::character varying, 'B1'::character varying, 'B2'::character varying, 'C1'::character varying, 'C2'::character varying])::text[])),
    goal            varchar(255)
        constraint additional_info_goal_check
            check ((goal)::text = ANY
                   ((ARRAY ['DEFAULT'::character varying, 'IMPROVE_ENGLISH'::character varying, 'LEARN_NEW_LANGUAGE'::character varying, 'MEET_NEW_PEOPLE'::character varying])::text[])),
    native_language varchar(255)
        constraint additional_info_native_language_check
            check ((native_language)::text = ANY
                   ((ARRAY ['ENGLISH'::character varying, 'SPANISH'::character varying, 'FRENCH'::character varying, 'GERMAN'::character varying, 'CHINESE'::character varying, 'JAPANESE'::character varying, 'RUSSIAN'::character varying, 'ARABIC'::character varying, 'PORTUGUESE'::character varying, 'HINDI'::character varying, 'UKRAINIAN'::character varying, 'POLISH'::character varying])::text[]))
);

create table if not exists users
(
    id                 varchar(255)                not null
        primary key,
    created_at         timestamp(6) with time zone not null,
    email_id           varchar(255)                not null
        constraint ukpwrpg821nujmmnavoq7s420jn
            unique,
    email_verified     boolean                     not null,
    last_login         timestamp(6) with time zone,
    password           varchar(255)                not null,
    provider           varchar(255)
        constraint users_provider_check
            check ((provider)::text = ANY ((ARRAY ['GOOGLE'::character varying, 'LOCAL'::character varying])::text[])),
    provider_id        varchar(255),
    roles              varchar(255)                not null,
    updated_at         timestamp(6) with time zone,
    user_name          varchar(255)                not null
        constraint ukk8d0f2n7n88w1a16yhua64onx
            unique,
    additional_info_id varchar(255)
        constraint ukkh2qhvfjauoj84wo0jaqo7hft
            unique
        constraint fknfppicjfye8gvyg76ktnm53yy
            references additional_info
);

create table if not exists verify_token
(
    token           varchar(255) not null
        primary key,
    delete_date     timestamp(6),
    email           varchar(255),
    expiration_date timestamp(6),
    token_type      varchar(255)
        constraint verify_token_token_type_check
            check ((token_type)::text = ANY
                   ((ARRAY ['Bearer'::character varying, 'PASSWORD_RESET'::character varying, 'EMAIL_VERIFICATION'::character varying])::text[]))
);

create table if not exists user_settings
(
    id                 varchar(255) not null
        primary key,
    interface_language varchar(255) not null
        constraint user_settings_interface_language_check
            check ((interface_language)::text = ANY
                   ((ARRAY ['ENGLISH'::character varying, 'SPANISH'::character varying, 'FRENCH'::character varying, 'GERMAN'::character varying, 'CHINESE'::character varying, 'JAPANESE'::character varying, 'RUSSIAN'::character varying, 'ARABIC'::character varying, 'PORTUGUESE'::character varying, 'HINDI'::character varying, 'UKRAINIAN'::character varying, 'POLISH'::character varying])::text[])),
    notifications      boolean      not null,
    theme              varchar(255)
        constraint user_settings_theme_check
            check ((theme)::text = ANY
                   ((ARRAY ['DARK'::character varying, 'BRIGHT'::character varying, 'CYAN'::character varying])::text[])),
    user_id            varchar(255)
        constraint uk4bos7satl9xeqd18frfeqg6tt
            unique
        constraint fk8v82nj88rmai0nyck19f873dw
            references users
);

create table if not exists refresh_token
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone,
    expires_at    timestamp(6) with time zone,
    refresh_token varchar(10000) not null,
    revoked       boolean,
    user_id       varchar(255)
        constraint fkjtx87i0jvq2svedphegvdwcuy
            references users
);